version: '3.4'

services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'rootpass'
            MYSQL_DATABASE: recipebook
            MYSQL_USER: serviceacct
            MYSQL_PASSWORD: password
        volumes:
            - dbdata:/var/lib/mysql
            - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
        restart: always

    recipebookserver:
        depends_on:
            - db
        image: recipebookserver/recipebookserver
        build:
            context: .
            dockerfile: recipebookserver/Dockerfile
        ports:
            - "5000:5000"

volumes:
    dbdata:
